Feature/#20 like song button
KieranBond/MiniSpotify pull request #22
Opened 2019-11-19 18:39 UTC by GabCM

Hello!

This adds a like/unlike button to the main interface, so the user can save and unsave the currently playing track into their Liked Songs library.

It is shown as a new heart icon that is placed at the right of the album art. It's shown as filled if the song is liked, or as an outline if it's not liked, just like in Spotify itself. Clicking on the heart switches the icon and does the saving/unsaving operation on the user's account.

Two scopes had to be added for the feature to work: 
- user-library-read
- user-library-modify

Hope you like it! Thank you!

Fixes #20

2019-11-19 22:37 UTC, KieranBond requested changes
This is looking great! Works like a charm too.

I think this is exactly how I would of implemented it and keeps completely in line with how the project is so I'll approve this after one thing - If you could just remove the changes to the `README.md` and add them perhaps into the Pull Request that would be great.

On the commit where you remove the ReadMe updates, it would be good to mention the scopes being modified too - Just to help keep the Git history useful.

Once that's done, I'm happy to merge this in :)

2019-11-20 15:44 UTC, GabCM commented
Alright so I brought the README.md file like before.

Thanks for the feedback! Much appreciated!

2019-11-20 15:44 UTC, KieranBond approved these changes

2019-11-20 15:45 UTC, KieranBond commented
Amazing, thanks @GabCM. Feel free to contribute more if there's anything you want added!

2019-11-20 15:45 UTC, merged