Added volume slider and repeat button.
KieranBond/MiniSpotify pull request #35
Opened 2021-03-31 20:22 UTC by MBlais13

Hope this one works, ill be adding a few other features in the future so ill try to figure out how to do this pr stuff on a private project.

2021-03-31 20:31 UTC, KieranBond commented
Thanks for tidying it up @MBlais13 . I'll take a look when I can - I had a brief peek at it yesterday and it looked good but I did have some thoughts.

I'd be happy to try and help explain the process, it can be quite confusing when you're new to it!

2021-03-31 20:51 UTC, MBlais13 commented
For sure. That would be super helpful if you could explain that to me, thanks!

2021-04-02 16:45 UTC, KieranBond requested changes
I've got a few thoughts below. Nothing major - Just some discussion points.

I love the idea behind the change though. 

Out of curiosity, how are you editing files? Are you using an IDE? I ask as there's a lot of formatting changes in these past two PR's; Formatting changes aren't a problem, they just make finding changes harder is all.

2021-04-02 16:45 UTC, KieranBond commented on MiniSpotify/MiniSpotify/Source/APIRequestor.cs
> +﻿using Microsoft.Win32;
Any idea why this whole file has seems to have been flagged as edited?

2021-04-02 16:45 UTC, KieranBond commented on MiniSpotify/MiniSpotify/Source/APIRequestor.cs
> +            int val = Convert.ToInt32(sv);
Nitpicky comment - Could we name this variable better?

2021-04-02 16:45 UTC, KieranBond commented on MiniSpotify/MiniSpotify/Source/APIRequestor.cs
> +        }
Isn't there 3 types of repeat? Repeat off, repeat once, repeat lots?

Would be good to have all 3 as an option.

2021-04-02 16:45 UTC, KieranBond commented on MiniSpotify/MiniSpotify/Source/MainWindow.xaml.cs
> +        public void Slider(FullTrack a_latestTrack = null)
What's the purpose of this empty function?

2021-04-06 18:12 UTC, KieranBond commented
@MBlais13 Hey Michael. I've just made a PR (and will be merging this in) that is likely going to break this branch big time.

Once I've merged my PR in - Would you like to just upload the assets/icons you had used in this PR and then I can add the functionality to them?

2021-04-06 20:12 UTC, MBlais13 commented
Is it possible to get your discord or something where we can chat about the PR easier? It seems like I've made this a bit more complicated than it should be.

2021-04-06 20:15 UTC, KieranBond commented
Absolutely. I've not helped in making this easy so perhaps Discord will be easier. Send me a friend request - Kieran#0012

2021-05-13 11:18 UTC, closed without merging